# Server Configuration
server:
  port: 9999
  error:
    include-stacktrace: always
  compression:
    enabled: true
  address: 0.0.0.0

# Spring Configuration
spring:
  application:
    name: starter-pack

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  # Database Configuration
  datasource:
    url: jdbc:h2:mem:mydb
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    url: jdbc:mysql://localhost:3306/demo?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
#    url: jdbc:sqlserver://localhost:1433;databaseName=IEIMS_DEV_ESURVEY_ONGOING
    username: sa
#    username: TEST
#    username: root
#    username: ieims_dev
    password: password
#    password: "test"
#    password:
#    password:
    driverClassName: org.h2.Driver
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    # Hikari Configuration
    hikari:
      minimum-idle: 1
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  # JPA Configuration
  jpa:
    # Properties
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.Oracle10gDialect
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: org.hibernate.dialect.SQLServer2012Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql: true
        shutdown_on_session_factory_close: false
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
          legacy_limit_handler: true

    # Hibernate
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
